services:
  - type: web
    name: laravel-seatbooking
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:oosRPcQDqCFQx6QXKs5L5qsEZvVO+krXo+NIkC2JtuM=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-internseat.alwaysdata.net
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: internseat_seatbooking
      - key: DB_USERNAME
        value: 425037
      - key: DB_PASSWORD
        value: u_kkyfEx3A*rksF
